// <auto-generated />
using System;
using Commodity_Request_Form.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Commodity_Request_Form.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250522162017_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Commodity_Request_Form.Models.CHA", b =>
                {
                    b.Property<int>("CHA_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CHA_ID"));

                    b.Property<string>("F_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("L_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CHA_ID");

                    b.ToTable("CHA");
                });

            modelBuilder.Entity("Commodity_Request_Form.Models.CHW", b =>
                {
                    b.Property<int>("CHW_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CHW_ID"));

                    b.Property<int>("CHA_ID")
                        .HasColumnType("int");

                    b.Property<string>("F_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("L_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CHW_ID");

                    b.HasIndex("CHA_ID");

                    b.ToTable("CHW");
                });

            modelBuilder.Entity("Commodity_Request_Form.Models.Commodity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CHA_ID")
                        .HasColumnType("int");

                    b.Property<int>("CHW_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CHA_ID");

                    b.HasIndex("CHW_ID");

                    b.ToTable("Commodity");
                });

            modelBuilder.Entity("Commodity_Request_Form.Models.CHW", b =>
                {
                    b.HasOne("Commodity_Request_Form.Models.CHA", "CHA")
                        .WithMany("CHWs")
                        .HasForeignKey("CHA_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CHA");
                });

            modelBuilder.Entity("Commodity_Request_Form.Models.Commodity", b =>
                {
                    b.HasOne("Commodity_Request_Form.Models.CHA", "CHA")
                        .WithMany("Commodities")
                        .HasForeignKey("CHA_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Commodity_Request_Form.Models.CHW", "CHW")
                        .WithMany("Commodities")
                        .HasForeignKey("CHW_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CHA");

                    b.Navigation("CHW");
                });

            modelBuilder.Entity("Commodity_Request_Form.Models.CHA", b =>
                {
                    b.Navigation("CHWs");

                    b.Navigation("Commodities");
                });

            modelBuilder.Entity("Commodity_Request_Form.Models.CHW", b =>
                {
                    b.Navigation("Commodities");
                });
#pragma warning restore 612, 618
        }
    }
}
