// <auto-generated />
using System;
using Commodity_Request_Form.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Commodity_Request_Form.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Commodity_Request_Form.Models.CHA", b =>
                {
                    b.Property<int>("CHA_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CHA_ID"));

                    b.Property<string>("F_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("L_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CHA_ID");

                    b.ToTable("CHA");

                    b.HasData(
                        new
                        {
                            CHA_ID = 1,
                            F_Name = "Alice",
                            L_Name = "Kamau"
                        },
                        new
                        {
                            CHA_ID = 2,
                            F_Name = "John",
                            L_Name = "Otieno"
                        },
                        new
                        {
                            CHA_ID = 3,
                            F_Name = "Mary",
                            L_Name = "Wangari"
                        },
                        new
                        {
                            CHA_ID = 4,
                            F_Name = "David",
                            L_Name = "Mwangi"
                        });
                });

            modelBuilder.Entity("Commodity_Request_Form.Models.CHW", b =>
                {
                    b.Property<int>("CHW_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CHW_ID"));

                    b.Property<int>("CHA_ID")
                        .HasColumnType("int");

                    b.Property<string>("F_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("L_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CHW_ID");

                    b.HasIndex("CHA_ID");

                    b.ToTable("CHW");

                    b.HasData(
                        new
                        {
                            CHW_ID = 1,
                            CHA_ID = 1,
                            F_Name = "Grace",
                            L_Name = "Njeri"
                        },
                        new
                        {
                            CHW_ID = 2,
                            CHA_ID = 2,
                            F_Name = "Peter",
                            L_Name = "Otieno"
                        },
                        new
                        {
                            CHW_ID = 3,
                            CHA_ID = 1,
                            F_Name = "Esther",
                            L_Name = "Wangari"
                        },
                        new
                        {
                            CHW_ID = 4,
                            CHA_ID = 3,
                            F_Name = "James",
                            L_Name = "Mwangi"
                        },
                        new
                        {
                            CHW_ID = 5,
                            CHA_ID = 4,
                            F_Name = "Faith",
                            L_Name = "Nyaoga"
                        },
                        new
                        {
                            CHW_ID = 6,
                            CHA_ID = 1,
                            F_Name = "Samuel",
                            L_Name = "Kamau"
                        },
                        new
                        {
                            CHW_ID = 7,
                            CHA_ID = 1,
                            F_Name = "Rebecca",
                            L_Name = "Nyambura"
                        },
                        new
                        {
                            CHW_ID = 8,
                            CHA_ID = 1,
                            F_Name = "David",
                            L_Name = "Owino"
                        },
                        new
                        {
                            CHW_ID = 9,
                            CHA_ID = 2,
                            F_Name = "Alice",
                            L_Name = "Kilonzo"
                        },
                        new
                        {
                            CHW_ID = 10,
                            CHA_ID = 2,
                            F_Name = "Michael",
                            L_Name = "Otieno"
                        },
                        new
                        {
                            CHW_ID = 11,
                            CHA_ID = 3,
                            F_Name = "Esther",
                            L_Name = "Ochieng"
                        },
                        new
                        {
                            CHW_ID = 12,
                            CHA_ID = 3,
                            F_Name = "Paul",
                            L_Name = "Ndegwa"
                        },
                        new
                        {
                            CHW_ID = 13,
                            CHA_ID = 4,
                            F_Name = "Joyce",
                            L_Name = "Akinyi"
                        },
                        new
                        {
                            CHW_ID = 14,
                            CHA_ID = 4,
                            F_Name = "Benjamin",
                            L_Name = "Mwangi"
                        });
                });

            modelBuilder.Entity("Commodity_Request_Form.Models.Commodity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CHA_ID")
                        .HasColumnType("int");

                    b.Property<int>("CHW_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CHA_ID");

                    b.HasIndex("CHW_ID");

                    b.ToTable("Commodity");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CHA_ID = 1,
                            CHW_ID = 1,
                            DateRequested = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Malaria Drugs",
                            Quantity = 50,
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            CHA_ID = 2,
                            CHW_ID = 2,
                            DateRequested = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Family Planning Items",
                            Quantity = 30,
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            CHA_ID = 1,
                            CHW_ID = 3,
                            DateRequested = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Zinc Tablets",
                            Quantity = 40,
                            Status = 2
                        },
                        new
                        {
                            ID = 4,
                            CHA_ID = 3,
                            CHW_ID = 4,
                            DateRequested = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Malaria Drugs",
                            Quantity = 60,
                            Status = 0
                        },
                        new
                        {
                            ID = 5,
                            CHA_ID = 4,
                            CHW_ID = 5,
                            DateRequested = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Family Planning Items",
                            Quantity = 25,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Commodity_Request_Form.Models.CHW", b =>
                {
                    b.HasOne("Commodity_Request_Form.Models.CHA", "CHA")
                        .WithMany("CHWs")
                        .HasForeignKey("CHA_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CHA");
                });

            modelBuilder.Entity("Commodity_Request_Form.Models.Commodity", b =>
                {
                    b.HasOne("Commodity_Request_Form.Models.CHA", "CHA")
                        .WithMany("Commodities")
                        .HasForeignKey("CHA_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Commodity_Request_Form.Models.CHW", "CHW")
                        .WithMany("Commodities")
                        .HasForeignKey("CHW_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CHA");

                    b.Navigation("CHW");
                });

            modelBuilder.Entity("Commodity_Request_Form.Models.CHA", b =>
                {
                    b.Navigation("CHWs");

                    b.Navigation("Commodities");
                });

            modelBuilder.Entity("Commodity_Request_Form.Models.CHW", b =>
                {
                    b.Navigation("Commodities");
                });
#pragma warning restore 612, 618
        }
    }
}
